generator/urls.py
from django.urls import path
from generator import views

app_name = 'generator'

urlpatterns = [
    path('home/', views.home, name='generator'),
    path('generatedpassword/', views.password, name='password'),
    path('about/', views.about, name='about'),
]

password_generator/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("generator.urls",namespace="generator")),
]

generator/models.py
from django.db import models

# Create your models here.

generator/views.py
from django.shortcuts import render
import random

# Create your views here.

def home(request):
    return render(request, 'generator/home.html')



def password(request):
    characters = list('abcdefghijklmnopqrstuvwxyz')
    uppers = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    numbers = list('0123456789')
    specials = list('!@#$%^&*()_+-=.,/?;:|`~')

    length = int(request.GET.get('length', 2))

    if request.GET.get('uppercase'):
        characters.extend(uppers)

    if request.GET.get('numbers'):
        characters.extend(numbers)

    if request.GET.get('special'):
        characters.extend(specials)

    thepassword = ''

    for x in range(length):
        thepassword += random.choice(characters)

    return render(request, 'generator/password.html', {'password': thepassword})

def about(request):
    return render(request, 'generator/about.html')

generator/templates/generator/about.html
<h1> This app is built by Uncle </h1>
<h2> uncle@uncle.com </h2>
<a href="{% url 'generator:generator' %}">Home</a>

generator/templates/generator/home.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="container text-center">
    <h1> Password Generator </h1>

    <form action="{% url 'generator:password' %}">
        <select name='length'>
            <option value='6'>6 </option>
            <option value='7'>7 </option>
            <option value='8'>8 </option>
            <option value='9'>9 </option>
            <option value='10'>10 </option>
            <option value='11'>11 </option>
            <option value='12' selected="selected">12 </option>
        </select> lenght
        <br>
        <input type='checkbox' name="uppercase">Uppercase
        <br>
        <input type='checkbox' name="numbers">Numbers
        <br>
        <input type='checkbox' name="special">Special Character
        <br>
        <input type="submit" value="Generate Password" class="btn btn-primary">
    </form>

    <a href="{% url 'generator:about' %}">About</a>
</div>

generator/templates/generator/password.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class="container text-center">

<h1> the password is : </h1>
<h2 class="alert alert-success"> {{ password }} </h2>
<a href="{% url 'generator:generator' %}" class="btn btn-warning">Home</a>
<a href="{% url 'generator:about' %}" class="btn btn-warning">About</a>

</div>